name: Test job
on: push

jobs:

  my_test_job:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - run: |
          pip install mp-api
          pip install black
          black --check .
          pip install pytest
          pytest test.py
